-- Seed 10 demo signals for UI validation
-- Run inside Supabase SQL editor after ensuring the trading_signals table exists.

with target_user as (
  select id
  from auth.users
  where id = '88fd09b4-9148-49ff-aafb-ad420d895dc0'
)
insert into public.trading_signals (
  id,
  user_id,
  symbol,
  timeframe,
  signal_type,
  signal_strength,
  confidence_score,
  entry_price,
  stop_loss_price,
  take_profit_price,
  risk_reward_ratio,
  technical_analysis,
  volume_analysis,
  pattern_analysis,
  ai_analysis,
  sentiment_analysis,
  confirmations,
  status,
  expires_at
)
select
  gen_random_uuid(),
  target_user.id,
  signals.symbol,
  signals.timeframe,
  signals.signal_type,
  signals.signal_strength,
  signals.confidence_score,
  signals.entry_price,
  signals.stop_loss_price,
  signals.take_profit_price,
  signals.risk_reward_ratio,
  signals.technical_analysis::jsonb,
  signals.volume_analysis::jsonb,
  signals.pattern_analysis::jsonb,
  signals.ai_analysis::jsonb,
  signals.sentiment_analysis::jsonb,
  signals.confirmations,
  signals.status,
  now() + (signals.expiry_hours || ' hours')::interval
from target_user
cross join (
  values
    ('BTC/USDT','1h','BUY','STRONG',82,98350,96500,101500,2.1,
      '{"rsi":32,"macd":0.003,"ema_20":98210,"ema_50":97500,"trend":"BULLISH"}',
      '{"volume_24h":5200000000,"volume_trend":"UP"}',
      '{"pattern_type":"Bullish Engulfing","pattern_strength":78}',
      '{"prediction":"Breakout","confidence":0.81}',
      '{"score":68,"trend":"IMPROVING"}',
      ARRAY['RSI','MACD','Pattern'],
      'ACTIVE', 6),
    ('ETH/USDT','1h','BUY','VERY_STRONG',90,3150,3020,3325,2.7,
      '{"rsi":28,"ema_20":3145,"ema_50":3090,"trend":"STRONG_UP"}',
      '{"volume_24h":2800000000,"whale_activity":true}',
      '{"pattern_type":"Ascending Triangle","breakout_probability":72}',
      '{"prediction":"Continuation","confidence":0.9}',
      '{"score":74,"trend":"POSITIVE"}',
      ARRAY['RSI','EMA','Triangle'],
      'ACTIVE', 8),
    ('SOL/USDT','4h','SELL','MODERATE',67,175,182,166,1.9,
      '{"rsi":71,"ema_20":176,"ema_50":169,"trend":"REVERSAL"}',
      '{"volume_24h":740000000}',
      '{"pattern_type":"Double Top","pattern_strength":65}',
      '{"prediction":"Pullback","confidence":0.64}',
      '{"score":42,"trend":"WEAKENING"}',
      ARRAY['RSI','Pattern'],
      'ACTIVE', 10),
    ('BNB/USDT','1h','BUY','VERY_STRONG',88,620,602,646,2.4,
      '{"rsi":34,"ema_20":619,"ema_50":612,"trend":"UP"}',
      '{"volume_24h":980000000}',
      '{"pattern_type":"Cup and Handle","pattern_strength":80}',
      '{"prediction":"Rally","confidence":0.87}',
      '{"score":70,"trend":"BULLISH"}',
      ARRAY['RSI','Pattern','EMA'],
      'ACTIVE', 5),
    ('XRP/USDT','4h','SELL','WEAK',58,1.22,1.27,1.15,1.4,
      '{"rsi":66,"ema_20":1.23,"ema_50":1.19,"trend":"FLAT"}',
      '{"volume_24h":400000000}',
      '{"pattern_type":"Rising Wedge","pattern_strength":60}',
      '{"prediction":"Correction","confidence":0.55}',
      '{"score":48,"trend":"NEUTRAL"}',
      ARRAY['RSI'],
      'ACTIVE', 12),
    ('ADA/USDT','1h','BUY','MODERATE',65,0.74,0.71,0.79,2.6,
      '{"rsi":36,"ema_20":0.735,"ema_50":0.721}',
      '{"volume_24h":320000000}',
      '{"pattern_type":"Flag","pattern_strength":58}',
      '{"prediction":"Bounce","confidence":0.63}',
      '{"score":52,"trend":"STABLE"}',
      ARRAY['RSI','EMA'],
      'ACTIVE', 6),
    ('MATIC/USDT','1h','BUY','STRONG',79,1.05,0.99,1.13,2.1,
      '{"rsi":33,"ema_20":1.03,"ema_50":0.97}',
      '{"volume_24h":210000000}',
      '{"pattern_type":"Inverse H&S","pattern_strength":75}',
      '{"prediction":"Breakout","confidence":0.79}',
      '{"score":66,"trend":"IMPROVING"}',
      ARRAY['Pattern','EMA'],
      'ACTIVE', 7),
    ('DOGE/USDT','30m','SELL','MODERATE',63,0.184,0.192,0.171,1.7,
      '{"rsi":72,"ema_20":0.186,"ema_50":0.182}',
      '{"volume_24h":150000000}',
      '{"pattern_type":"Parabolic","pattern_strength":58}',
      '{"prediction":"Cool-off","confidence":0.6}',
      '{"score":40,"trend":"OVERBOUGHT"}',
      ARRAY['RSI'],
      'ACTIVE', 4),
    ('AVAX/USDT','1h','BUY','VERY_STRONG',86,48.5,46.2,52.8,2.35,
      '{"rsi":31,"ema_20":48.1,"ema_50":46.9}',
      '{"volume_24h":560000000}',
      '{"pattern_type":"Channel Break","pattern_strength":82}',
      '{"prediction":"Trend Resumption","confidence":0.84}',
      '{"score":69,"trend":"POSITIVE"}',
      ARRAY['RSI','Channel'],
      'ACTIVE', 9),
    ('OP/USDT','4h','SELL','STRONG',76,1.95,2.05,1.78,1.8,
      '{"rsi":69,"ema_20":1.97,"ema_50":1.85}',
      '{"volume_24h":190000000}',
      '{"pattern_type":"Lower Highs","pattern_strength":70}',
      '{"prediction":"Retracement","confidence":0.74}',
      '{"score":45,"trend":"COOLING"}',
      ARRAY['RSI','EMA'],
      'ACTIVE', 11)
) AS signals(symbol, timeframe, signal_type, signal_strength, confidence_score,
 entry_price, stop_loss_price, take_profit_price, risk_reward_ratio,
 technical_analysis, volume_analysis, pattern_analysis, ai_analysis,
 sentiment_analysis, confirmations, status, expiry_hours)
ON CONFLICT DO NOTHING;

