-- Create AI Ultra Signals history table
create table if not exists public.ai_signals_history (
  id uuid primary key default gen_random_uuid(),
  symbol text not null,
  timeframe text not null,
  side text not null,
  final_confidence numeric not null,
  risk_level text not null,
  entry_price numeric,
  stop_loss numeric,
  take_profit numeric,
  rr_ratio numeric,
  ai_score numeric,
  technical_score numeric,
  volume_score numeric,
  pattern_score numeric,
  wave_score numeric,
  sentiment_score numeric,
  sources_used jsonb,
  result text,
  profit_loss_percentage numeric,
  closed_at timestamptz,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

comment on table public.ai_signals_history is 'Stores Ultra Signal outputs generated by the AI engine';

create index if not exists ai_signals_history_symbol_idx on public.ai_signals_history (symbol);
create index if not exists ai_signals_history_timeframe_idx on public.ai_signals_history (timeframe);
create index if not exists ai_signals_history_side_idx on public.ai_signals_history (side);
create index if not exists ai_signals_history_created_at_idx on public.ai_signals_history (created_at desc);

alter table public.ai_signals_history
  enable row level security;

drop policy if exists "ai_signals_history service access" on public.ai_signals_history;
drop policy if exists "ai_signals_history read" on public.ai_signals_history;
drop policy if exists "ai_signals_history insert" on public.ai_signals_history;
drop policy if exists "ai_signals_history update" on public.ai_signals_history;

create policy "ai_signals_history read"
  on public.ai_signals_history
  for select
  to authenticated
  using (true);

create policy "ai_signals_history insert"
  on public.ai_signals_history
  for insert
  to service_role
  with check (true);

create policy "ai_signals_history update"
  on public.ai_signals_history
  for update
  to service_role
  using (true)
  with check (true);

-- AI Signal user settings storage
create table if not exists public.ai_signal_user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  smart_mode_enabled boolean not null default true,
  global_settings jsonb not null default '{}'::jsonb,
  timeframe_profiles jsonb not null default '{}'::jsonb,
  weight_presets jsonb not null default '{}'::jsonb,
  last_reset_at timestamptz,
  signal_source text not null default 'ai',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

comment on table public.ai_signal_user_settings is 'Stores custom indicator/fusion settings per user';

create index if not exists ai_signal_user_settings_signal_source_idx on public.ai_signal_user_settings (signal_source);

alter table public.ai_signal_user_settings
  enable row level security;

drop policy if exists "ai_signal_settings_self" on public.ai_signal_user_settings;

create policy "ai_signal_settings_self"
  on public.ai_signal_user_settings
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.update_ai_signal_settings_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_ai_signal_settings_updated on public.ai_signal_user_settings;

create trigger trg_ai_signal_settings_updated
  before update on public.ai_signal_user_settings
  for each row execute function public.update_ai_signal_settings_updated_at();

