// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to hardcoded values for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pjgfrhgjbbsqsmwfljpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZ2ZyaGdqYmJzcXNtd2ZsanBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMjUxMjMsImV4cCI6MjA4MDgwMTEyM30.sA925bnHvb3RP4b2RYyUDj73icuDUtIlRFXc1AcQ7Uw";

/**
 * Validate Supabase key by decoding JWT and checking role
 * Phase X.15 - Security: Improved key validation
 */
function validateSupabaseKey(key: string): { isValid: boolean; isAnon: boolean; error?: string } {
  try {
    // JWT tokens have 3 parts separated by dots
    const parts = key.split('.');
    if (parts.length !== 3) {
      return { isValid: false, isAnon: false, error: 'Invalid JWT format' };
    }

    // Decode the payload (second part)
    const payload = JSON.parse(atob(parts[1]));

    // Check if it's a Supabase token
    if (payload.iss !== 'supabase') {
      return { isValid: false, isAnon: false, error: 'Not a Supabase token' };
    }

    // Check the role
    const role = payload.role;
    const isAnon = role === 'anon';
    const isServiceRole = role === 'service_role';

    if (isServiceRole) {
      return {
        isValid: false,
        isAnon: false,
        error: 'SECURITY WARNING: service_role key detected! This should NEVER be used in client-side code.'
      };
    }

    return { isValid: true, isAnon };
  } catch (error) {
    // If we can't decode, it might still be valid (could be a different format)
    // But we'll be cautious and check length as fallback
    if (key.length > 500) {
      return {
        isValid: false,
        isAnon: false,
        error: 'Key seems unusually long. Please verify you are using anon key.'
      };
    }
    return { isValid: true, isAnon: true }; // Assume valid if we can't decode
  }
}

// Validate key in development mode only
if (import.meta.env.DEV && SUPABASE_PUBLISHABLE_KEY) {
  const validation = validateSupabaseKey(SUPABASE_PUBLISHABLE_KEY);

  if (!validation.isValid) {
    console.error('❌ Supabase Key Validation Failed:', validation.error);
  } else if (validation.isAnon) {
    // Only log success in dev mode, no warnings
    console.log('✅ Supabase client initialized with anon key');
  }

  // Only log URL in dev mode
  console.log('🔗 Supabase URL:', SUPABASE_URL);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'orbitra-ai@1.0.0',
    },
  },
});